model_name: MOE
train_router_only: True
router: 
  name: TrajAttentionRouter
  k: 1
past_len: 21 # history trajectory length, 2.1s
future_len: 60 # future trajectory length, 6s
num_experts: 2
center_offset_of_map: [ 30.0, 0.0 ] 
in_channels: 256
hidden_size: 256
num_queries_enc: 192
num_map_feature: 29
num_agent_feature: 39
num_queries_dec: 64
max_num_roads: 384
max_num_agents: 32
train_batch_size: 8
eval_batch_size: 8
max_epochs: 40
grad_clip_norm: 5
learning_rate: 0.00075 # 0.00075 # 1e-3 for lanegcn
learning_rate_sched: [ 10, 20, 30, 40, 50 ]
optimizer: Adam #According to PyTorch naming
scheduler: multistep # plateau, multistep
eval_nuscenes: False # whether to evaluate with nuscenes evaluation tool
eval_waymo: False # whether to evaluate with waymo evaluation tool
eval_argoverse2: False # whether to evaluate with argoverse evaluation tool

experts_cfg:
      - type: autobot
        method:
            model_name: autobot
        num_modes: 6
        past_len: 21 # history trajectory length, 2.1s
        future_len: 60 # future trajectory length, 6s
        hidden_size: 128
        num_encoder_layers: 2
        num_decoder_layers: 2
        tx_hidden_size: 384
        tx_num_heads: 16
        dropout: 0.1
        entropy_weight: 40.0
        kl_weight: 20.0
        use_FDEADE_aux_loss: True
        max_epochs: 150 #150 #40
        learning_rate: 0.00075 # 0.00075 # 1e-3 for lanegcn
        learning_rate_sched: [ 10, 20, 30, 40, 50 ]
        optimizer: Adam #According to PyTorch naming
        scheduler: multistep # plateau, multistep
        ewc_lambda: 2000
        train_batch_size: 8 #32 #128
        eval_batch_size: 8 #32 #128
        grad_clip_norm: 5
        max_num_agents: 15
        map_range: 100
        max_num_roads: 256
        max_points_per_lane: 20 # will be overwritten if manually_split_lane is True
        # lane split related params
        manually_split_lane: False # if True, lanes will be split with the same number of points and length, else, lanes will be split with the same number of points but varying length
        point_sampled_interval: 1 # only used when manually_split_lane is True, the interval of points sampled from the original lane
        num_points_each_polyline: 20 # only used when manually_split_lane is True, the number of points in each polyline
        vector_break_dist_thresh: 1.0 # only used when manually_split_lane is True, the distance threshold to break the vector to split the lane
        init_cfg:
          type: Pretrained
          checkpoint: /home/zzs/zzs/unitraj_ckpt/autobot_mini/epoch=16-val/brier_fde=6.42-val/minFDE6=5.72-val/minADE6=2.42.ckpt

      - type: wayformer
        past_len: 21 # history trajectory length, 2.1s
        future_len: 60 # future trajectory length, 6s
        method:
            model_name: wayformer
        # model
        use_map_image: False
        use_map_lanes: True
        num_modes: 6
        num_agent_feature: 39
        num_map_feature: 29
        hidden_size: 256
        num_encoder_layers: 2
        num_decoder_layers: 8
        tx_hidden_size: 1024
        tx_num_heads: 4
        dropout: 0.1
        entropy_weight: 40.0
        kl_weight: 20.0
        use_FDEADE_aux_loss: True
        num_queries_dec: 64
        num_queries_enc: 192

        # train
        max_epochs: 40 #150 #40
        learning_rate: 0.0001 # 0.00075 # 1e-3 for lanegcn
        learning_rate_sched: [ 10, 20, 30, 40, 50 ]
        optimizer: AdamW #According to PyTorch naming
        scheduler: multistep # plateau, multistep
        ewc_lambda: 2000
        grad_clip_norm: 5
        train_batch_size: 8 #32 #128
        eval_batch_size: 8 #32 #128

        # data related
        max_num_agents: 32
        map_range: 100
        max_num_roads: 384
        max_points_per_lane: 30 # will be overwritten if manually_split_lane is True
        manually_split_lane: False
        # lane split related params
        point_sampled_interval: 1
        num_points_each_polyline: 20
        vector_break_dist_thresh: 1.0
        init_cfg:
            type: Pretrained
            checkpoint: /home/zzs/zzs/unitraj_ckpt/wayformer_baseline/epoch=39-val/brier_fde=6.02-val/minFDE6=5.40-val/minADE6=2.45.ckpt


 
        
        # common
      - type: MTR
        method:
            model_name: MTR
        past_len: 21 # history trajectory length, 2.1s
        future_len: 60 # future trajectory length, 6s
        # model
        center_offset_of_map: [ 30.0, 0.0 ] 
        object_type: [ 'VEHICLE' ]
        CONTEXT_ENCODER:
          NAME: MTREncoder
          NUM_OF_ATTN_NEIGHBORS: 7
          NUM_INPUT_ATTR_AGENT: 39
          NUM_INPUT_ATTR_MAP: 29
          NUM_CHANNEL_IN_MLP_AGENT: 256
          NUM_CHANNEL_IN_MLP_MAP: 64
          NUM_LAYER_IN_MLP_AGENT: 3
          NUM_LAYER_IN_MLP_MAP: 5
          NUM_LAYER_IN_PRE_MLP_MAP: 3
          D_MODEL: 256
          NUM_ATTN_LAYERS: 6
          NUM_ATTN_HEAD: 8
          DROPOUT_OF_ATTN: 0.1
          USE_LOCAL_ATTN: True

        MOTION_DECODER:
          NAME: MTRDecoder
          NUM_MOTION_MODES: 6
          INTENTION_POINTS_FILE: '/home/zzs/zzs/unitraj__MOE/unitraj/models/mtr/cluster_64_center_dict_6s.pkl'
          D_MODEL: 512
          NUM_DECODER_LAYERS: 6
          NUM_ATTN_HEAD: 8
          MAP_D_MODEL: 256
          DROPOUT_OF_ATTN: 0.1
          NUM_BASE_MAP_POLYLINES: 256
          NUM_WAYPOINT_MAP_POLYLINES: 128
          LOSS_WEIGHTS: {
            'cls': 1.0,
            'reg': 1.0,
            'vel': 0.5
          }

          NMS_DIST_THRESH: 2.5

        # train
        max_epochs: 40
        learning_rate: 0.0001
        learning_rate_sched: [ 22, 24, 26, 28 ]
        optimizer: AdamW
        scheduler: lambdaLR
        grad_clip_norm: 1000.0
        weight_decay: 0.01
        lr_decay: 0.5
        lr_clip: 0.000001
        WEIGHT_DECAY: 0.01
        train_batch_size: 8 #32 #128
        eval_batch_size: 8 #32 #128

        # data related
        max_num_agents: 64
        map_range: 100
        max_num_roads: 768

        # will be overwritten if manually_split_lane is True
        max_points_per_lane: 20

        manually_split_lane: True
        point_sampled_interval: 1
        num_points_each_polyline: 20
        vector_break_dist_thresh: 1.0
        init_cfg:
          type: Pretrained
          checkpoint: /home/zzs/zzs/unitraj__MOE/unitraj_ckpt/MTR_mini_baseline/epoch=38-val/brier_fde=2.39-val/minFDE6=2.08-val/minADE6=0.90.ckpt





